[2023-10-28T21:32:24.297+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-10-28T16:27:04.141821+00:00 [queued]>
[2023-10-28T21:32:24.301+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-10-28T16:27:04.141821+00:00 [queued]>
[2023-10-28T21:32:24.301+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-28T21:32:24.311+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-10-28 16:27:04.141821+00:00
[2023-10-28T21:32:24.314+0500] {standard_task_runner.py:57} INFO - Started process 13998 to run task
[2023-10-28T21:32:24.317+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-10-28T16:27:04.141821+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp6mqad38w']
[2023-10-28T21:32:24.318+0500] {standard_task_runner.py:85} INFO - Job 29: Subtask train_model
[2023-10-28T21:32:24.346+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-10-28T16:27:04.141821+00:00 [running]> on host xFlow.xFlow.virtualbox.org
[2023-10-28T21:32:24.383+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-10-28T16:27:04.141821+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-28T16:27:04.141821+00:00'
[2023-10-28T21:32:24.384+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-28T21:32:24.385+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/termik/project/scripts/train_model.py']
[2023-10-28T21:32:24.390+0500] {subprocess.py:86} INFO - Output:
[2023-10-28T21:32:25.008+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-28T21:32:25.009+0500] {subprocess.py:93} INFO -   File "/home/termik/project/scripts/train_model.py", line 11, in <module>
[2023-10-28T21:32:25.009+0500] {subprocess.py:93} INFO -     with open('/home/termik/project/models/data.pickle', 'wb') as f:
[2023-10-28T21:32:25.009+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/termik/project/models/data.pickle'
[2023-10-28T21:32:25.108+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-28T21:32:25.112+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/termik/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-28T21:32:25.114+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231028T162704, start_date=20231028T163224, end_date=20231028T163225
[2023-10-28T21:32:25.124+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 13998)
[2023-10-28T21:32:25.138+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-28T21:32:25.148+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
