[2023-10-28T21:58:06.470+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-10-28T16:58:03.335906+00:00 [queued]>
[2023-10-28T21:58:06.474+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-10-28T16:58:03.335906+00:00 [queued]>
[2023-10-28T21:58:06.475+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-28T21:58:06.486+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-10-28 16:58:03.335906+00:00
[2023-10-28T21:58:06.489+0500] {standard_task_runner.py:57} INFO - Started process 21112 to run task
[2023-10-28T21:58:06.493+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-10-28T16:58:03.335906+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpp2ycr0be']
[2023-10-28T21:58:06.495+0500] {standard_task_runner.py:85} INFO - Job 39: Subtask get_data
[2023-10-28T21:58:06.532+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-10-28T16:58:03.335906+00:00 [running]> on host xFlow.xFlow.virtualbox.org
[2023-10-28T21:58:06.581+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-28T16:58:03.335906+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-28T16:58:03.335906+00:00'
[2023-10-28T21:58:06.583+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-28T21:58:06.583+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/termik/project/scripts/get_data.py']
[2023-10-28T21:58:06.589+0500] {subprocess.py:86} INFO - Output:
[2023-10-28T21:58:07.689+0500] {subprocess.py:93} INFO - /home/termik/project/venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-10-28T21:58:07.689+0500] {subprocess.py:93} INFO - 
[2023-10-28T21:58:07.690+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-10-28T21:58:07.690+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-10-28T21:58:07.697+0500] {subprocess.py:93} INFO - /home/termik/project/venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
[2023-10-28T21:58:07.697+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-10-28T21:58:07.697+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-10-28T21:58:14.223+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-28T21:58:14.238+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231028T165803, start_date=20231028T165806, end_date=20231028T165814
[2023-10-28T21:58:14.261+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-28T21:58:14.277+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
