[2023-10-28T21:21:15.803+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [queued]>
[2023-10-28T21:21:15.808+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [queued]>
[2023-10-28T21:21:15.809+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-28T21:21:15.820+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_test_split_data> on 2023-10-28 16:10:57.097935+00:00
[2023-10-28T21:21:15.824+0500] {standard_task_runner.py:57} INFO - Started process 10943 to run task
[2023-10-28T21:21:15.827+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_test_split_data', 'manual__2023-10-28T16:10:57.097935+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpya2t_m3i']
[2023-10-28T21:21:15.829+0500] {standard_task_runner.py:85} INFO - Job 24: Subtask train_test_split_data
[2023-10-28T21:21:15.859+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [running]> on host xFlow.xFlow.virtualbox.org
[2023-10-28T21:21:15.900+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_test_split_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-28T16:10:57.097935+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-28T16:10:57.097935+00:00'
[2023-10-28T21:21:15.901+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-28T21:21:15.901+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/termik/project/scripts/train_test_split_data.py']
[2023-10-28T21:21:15.909+0500] {subprocess.py:86} INFO - Output:
[2023-10-28T21:21:15.923+0500] {subprocess.py:93} INFO - python3: can't open file '/home/termik/project/scripts/train_test_split_data.py': [Errno 2] No such file or directory
[2023-10-28T21:21:15.926+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-28T21:21:15.931+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/termik/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-28T21:21:15.934+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_test_split_data, execution_date=20231028T161057, start_date=20231028T162115, end_date=20231028T162115
[2023-10-28T21:21:15.946+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task train_test_split_data (Bash command failed. The command returned a non-zero exit code 2.; 10943)
[2023-10-28T21:21:15.969+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-28T21:21:15.982+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
