[2023-10-28T21:16:13.899+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [queued]>
[2023-10-28T21:16:13.907+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [queued]>
[2023-10-28T21:16:13.907+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-28T21:16:13.922+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_test_split_data> on 2023-10-28 16:10:57.097935+00:00
[2023-10-28T21:16:13.925+0500] {standard_task_runner.py:57} INFO - Started process 9835 to run task
[2023-10-28T21:16:13.928+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_test_split_data', 'manual__2023-10-28T16:10:57.097935+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp9l_7og4h']
[2023-10-28T21:16:13.929+0500] {standard_task_runner.py:85} INFO - Job 22: Subtask train_test_split_data
[2023-10-28T21:16:13.961+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_test_split_data manual__2023-10-28T16:10:57.097935+00:00 [running]> on host xFlow.xFlow.virtualbox.org
[2023-10-28T21:16:14.007+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_test_split_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-28T16:10:57.097935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-28T16:10:57.097935+00:00'
[2023-10-28T21:16:14.009+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-28T21:16:14.009+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/termik/project/scripts/train_test_split_data.py']
[2023-10-28T21:16:14.017+0500] {subprocess.py:86} INFO - Output:
[2023-10-28T21:16:14.032+0500] {subprocess.py:93} INFO - python3: can't open file '/home/termik/project/scripts/train_test_split_data.py': [Errno 2] No such file or directory
[2023-10-28T21:16:14.035+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-28T21:16:14.040+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/termik/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-28T21:16:14.043+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_test_split_data, execution_date=20231028T161057, start_date=20231028T161613, end_date=20231028T161614
[2023-10-28T21:16:14.055+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task train_test_split_data (Bash command failed. The command returned a non-zero exit code 2.; 9835)
[2023-10-28T21:16:14.064+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-28T21:16:14.077+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
